version: '2.0'
services:
  qb:
    container_name: qb
    build: .
    restart: unless-stopped
    volumes:
      - ./assets:/app/assets
      - ./logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      